### PR TITLE
fixes and improvements

### PR DESCRIPTION
**Pull request by FarzeenKist**
## Fixes and Improvements
1.  Improved documentation of code by removing redundant variables, and functions, typo fixes, and added comments in the Nat spec format.
2. Added the struct Comment to keep track of the owner of a comment
3. Grouped common checks into their modifiers while also improving the gas costs throughout the smart contract(storing strings to calldata, doing complex mathematical operations on a variable in memory then assigning to the respective variable in storage and using storage pointers)
4. I've added the mapping to keep which users liked a story to prevent a user from spamming the likes and dislikes functionalities. This also helps in improving the accuracy of data
5. There was a bug when deleting a story where the variable numberOfStories(previously numberOfEvents) was being decremented. This could lead to issues where existing stories would be overridden when calling the createStory functions

### CODE REVIEW

**Comment by ArtFeltWave** [comment]
Thanks @FarzeenKist 
I have been trying to implement the support functionality in the frontend and I have been unsuccessful thus i disabled the button 
Can you pls look through to see where i made a mistake 



also in implementing the delete-story functionality ,after the story is deleted, the remaining stories are not rendered

**Comment by ArtFeltWave** [comment]
Pardon me, I’m relatively new to the tech space

**Comment by ArtFeltWave** [comment]
Thanks @FarzeenKist <https://github.com/FarzeenKist>
I have been trying to implement the support functionality in the frontend
and I have been unsuccessful thus i disabled the button
Can you pls look through to see where i made a mistake

also in implementing the delete-story functionality ,after the story is
deleted, the remaining stories are not rendered


Pls pardon me, I’m new to tech and this is my very first project

**Comment by FarzeenKist** [comment]
Hello @ArtFeltWave, the retrieval issue you had can be solved by modifying the eraseStory function to this (It will reorder your mapping which should solve the retrieval issue after deleting a story):

```js 
   /// @dev allow story owners to delete a story from the platform
    /// @notice story with _index will become inaccessible
    function eraseStory(uint256 _index)
        public
        exist(_index)
        checkIfOwner(_index)
    {
        uint256 newnumberOfStories = numberOfStories - 1;
        numberOfStories = newnumberOfStories;
        stories[_index] = stories[newnumberOfStories];
        delete (stories[newnumberOfStories]);
        exists[newnumberOfStories] = false;
    }
```
    
As for implementing the support function on your front end. I believe the issue stems from you using the same id for all your CTA buttons(edit, delete, and support buttons). The issue with that is that ids conflict with each other as ids are supposed to be unique. You could fix the issue by doing something like:
 
`id="edit-${product.index}"`

and then retrieve the index by doing something like this (the reason we are using the number 5 to slice is that the character "-" starts at the index 4 in "edit-" which means that we need to increment it to the index 5 to avoid the slicing to start with "-"):

`let index = e.target.id;
index = index.slice(5);`


[Slice definition on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice)


Good luck and let me know if you have any other questions/issues.

**Comment by ArtFeltWave** [comment]
Thank you so much
I’m currently following your instructions
I will send you A report soon

**Pull request merged**
